### ISSUE TITLE
Support navigator.keyboard.lock on https://w3c.github.io/uievents/tools/key-event-viewer.html

### ISSUE THREAD

**Issue by jamiewalch** [garykac/dom-event-viewer#1]
It would be useful to be able to see the keyevents received when keyboard lock is active. To this end, a button to activate keyboard lock and full-screen would be useful. Currently it's possible to do this via the JS console:

navigator.keyboard.lock()
document.body.requestFullscreen()

**Comment by garykac** [comment]
Added buttons for Fullscreen and KeyboardLock in 85b84183017f66f986e63822ce90720602b72285
